#MySQL 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/articles
    username: ${DB_USER}
    password: ${DB_PW}
  sql:
    init:
      mode: never
    # 정렬 방식
    # always 항상 , embedded : 그장 DB만 never : 모든 동작 안함
  jpa:
    # spring.sql.init 초기화 할때 데이터 입력을 위한 리 작업을 배치 할것
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

